### ISSUE TITLE
Lack of information

### ISSUE THREAD

**Issue by Dragnucs** [ProcessMaker/nayra#119]
Hello,

I am interested in developing some advanced workflows in ProcessMaker and came across your repository. However, I am confused as to what purpose it serves.

I know about ProcessMaker and been using for a while to create some of our workflows at work. And your code seem to be of interest.

However, i am unsure about the following:

- What is the exact purpose of nayra?
- Are you from ProcessMaker, affiliated or unrelated?
- How is this different from Colosa?
- Is this project intended to be used by PM software itself, by third party developers for plusings, etc.?
- How is using nyara different from regular PM designer, triggers?
- How do I even use this?

I am really interested in having a full-code project that can live inside Git rather than creating the workflow by drag'n'drop. Bonus points if I can do both.

**Comment by velkymx** [comment]
@Dragnucs head over to the bpm project and give it a try. https://github.com/ProcessMaker/bpm

**Comment by tdondich** [comment]
Hi @Dragnucs , the nayra project is the high performance PHP based workflow engine used in the upcoming ProcessMaker BPM 4 project.  It is BPMN compliant and 100% unit tested.  Nayra can be used as an embedded workflow engine that is BPMN2 compliant.  You'll need to build out the data repositories based on the interfaces that Nayra expects, then load a BPMN file using the interfaces and off you go!  We're looking at building further documentation for this style of integration moving forward, but for now you can look at the bpm project to see how it's implemented.   The test cases also help to understand it's usage.

If you need something that is full featured, the ProcessMaker BPM project is what you are looking for.  This includes a full web interface with drag and drop modeling, etc.  It's built as a Laravel application which means you can develop packages to extend it's interface and add new functionality.

We're absolutely looking for contributors so if you're interested in using nayra, we can always use contributions in the form of bug tickets, documentation and feature requests.

**Comment by Dragnucs** [comment]
Thank you very much for the clarifications.
