### ISSUE TITLE
Implement default final model classes for flow collaboration and other elements

### ISSUE THREAD

**Issue by danloa** [ProcessMaker/nayra#66]
As a developer, I would like to have ready to use classes to load and execute BPMN processes.

Implement default final repository classes for BPMN element. For:

Collaboration and other elements
- RootElements
- EventDefinitions
- ExecutionElements

**Comment by caleeli** [comment]
The list of classes and required changes are the following:

- Refactor the Collaboration class to move it from **tests/ProcessMaker/Models/Collaboration.php** to **src/ProcessMaker/Bpmn/Model/Collaboration.php**
- Refactor the ItemDefinition class to move it from  **src/ProcessMaker/Nayra/Bpmn/ItemDefinition.php** to **src/ProcessMaker/Nayra/Bpmn/Model/ItemDefinition.php**
- Refactor then Message class to move it from **tests/ProcessMaker/Models/Message.php** to **src/ProcessMaker/Nayra/Bpmn/Model/Message.php**
- Refactor the MessageEventDefinition class to move it from **src/ProcessMaker/Nayra/Bpmn/MessageEventDefinition.php** to **src/ProcessMaker/Nayra/Bpmn/Model/MessageEventDefinition.php**
- Refactor the FormalExpression class to move it from **tests/ProcessMaker/Models/FormalExpression.php** to **src/ProcessMaker/Nayra/Bpmn/Model/FormalExpression.php**
- Refactor the Signal class to move it from **tests/ProcessMaker/Models/Signal.php** to **src/ProcessMaker/Nayra/Bpmn/Model/Signal.php**
- Refactor the SignalEventDefinition class to move it from **src/ProcessMaker/Nayra/Bpmn/SignalEventDefinition.php** to **src/ProcessMaker/Nayra/Bpmn/Model/SignalEventDefinition.php**
- Refactor the ConditionalEventDefinition class to move it from **src/ProcessMaker/Nayra/Bpmn/ConditionalEventDefinition.php** to **src/ProcessMaker/Nayra/Bpmn/Model/ConditionalEventDefinition.php**
- Refactor the TerminateEventDefinition class to move it from **src/ProcessMaker/Nayra/Bpmn/TerminateEventDefinition.php** to **src/ProcessMaker/Nayra/Bpmn/Model/TerminateEventDefinition.php**
- Refactor the ErrorEventDefinition class to move it from **src/ProcessMaker/Nayra/Bpmn/ErrorEventDefinition.php** to **src/ProcessMaker/Nayra/Bpmn/Model/ErrorEventDefinition.php**
- Refactor the Error class to move it from **tests/ProcessMaker/Models/Error.php** to **src/ProcessMaker/Nayra/Bpmn/Model/Error.php**
- Refactor the TimerEventDefinition class to move it from **src/ProcessMaker/Nayra/Bpmn/TimerEventDefinition.php** to **src/ProcessMaker/Nayra/Bpmn/Model/TimerEventDefinition.php**
- Refactor the Participant class to move it from **tests/ProcessMaker/Models/Participant.php** to **src/ProcessMaker/Nayra/Bpmn/Model/Participant.php**
- Remove from Participant class the usage of the traits LocalFlowNodeTrait and LocalPropertiesTrait, they are not required more.
- Verify that all the unit tests are running.
